//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.13 at 12:32:13 PM AEDT 
//


package com.titanhelix.mathematica.ws.mathematica;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.titanhelix.mathematica.ws.mathematica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.titanhelix.mathematica.ws.mathematica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGcdSumResponse }
     * 
     */
    public GetGcdSumResponse createGetGcdSumResponse() {
        return new GetGcdSumResponse();
    }

    /**
     * Create an instance of {@link GetGcdSumRequest }
     * 
     */
    public GetGcdSumRequest createGetGcdSumRequest() {
        return new GetGcdSumRequest();
    }

    /**
     * Create an instance of {@link GetGcdListResponse }
     * 
     */
    public GetGcdListResponse createGetGcdListResponse() {
        return new GetGcdListResponse();
    }

    /**
     * Create an instance of {@link GetGcdListRequest }
     * 
     */
    public GetGcdListRequest createGetGcdListRequest() {
        return new GetGcdListRequest();
    }

    /**
     * Create an instance of {@link GetGcdRequest }
     * 
     */
    public GetGcdRequest createGetGcdRequest() {
        return new GetGcdRequest();
    }

    /**
     * Create an instance of {@link GetGcdResponse }
     * 
     */
    public GetGcdResponse createGetGcdResponse() {
        return new GetGcdResponse();
    }

}
