//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.09 at 05:51:34 PM AEDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mathematica.titanhelix.com/ws/mathematica-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.titanhelix.mathematica.ws.mathematica_soap;
